export const DateFormats = {
    yyyyMMDD: 'yyyy-MM-DD',
    YYYYMMDD: 'YYYY-MM-DD',
    YYYYDDMO: 'YYYY-DD-MO',
    doMMMYYYY: 'Do MMM YYYY',
    DDMMMddd: 'DD MMM, ddd',
    dddDDMMM: 'ddd, DD MMM',
    dddDDMMMHHmm: 'ddd, DD MMM HH:mm',
    MMDDYYYYHHMM: 'MM/DD/YYYY hh:mm:ss a',
    DDMMMyyyy: 'DD MMM yyyy',
    DDMMMYYYY: 'DD-MMM-yyyy',
    DoMMMYYYY: 'DD MMM, YYYY',
    DdMMMyyyy: 'DD-MMM, YYYY',
    DdMMMyyyHHmm: 'DD-MMM YYYY HH:mm',
    DDMMYYYY: 'DD/MM/YYYY',
    DDMMM: 'DD MMM',
    DDMMMM: 'DD MMMM',
    HHmm: 'HH:mm',
    HHmmss: 'HH:mm:ss',
    DDMMMYY: 'DD MMM, YY',
    MMMM: 'MMMM',
    MMYY: 'MMYY',
    MMMD: 'MMM D',
    DD: 'DD',
    HH: 'HH',
    HMMA: 'h:mm A',
    MMDDYYYYhhmmssA: 'MM/DD/YYYY hh:mm:ss A',
    DDD: 'ddd',
    dddDDMMMYYYY: 'ddd, DD MMM YYYY',
};